version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: maven:3.8.4-openjdk-11

    steps:
      - checkout
      - run:
          name: Run Maven Tests
          command: mvn test
      - store_artifacts:
          path: target
      - codecov/upload

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master