# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8-jdk-8

    branches:
      only:
        - master

    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            mvn clean  # Nettoyer les artefacts précédents
            mvn test   # Exécuter les tests unitaires
