# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-openjdk-11

    steps:
      - checkout
      - run:
          name: Display Java Version
          command: java -version
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Unit Tests
          command: | 
            mvn test
      - run:
          name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: $CODECOV_TOKEN
            slug: YoussefHannachii/ceri-m1-techniques-de-test