version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-openjdk-11

    steps:
      - checkout
      - run:
          name: Display Java Version
          command: java -version
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Unit Tests
          command: mvn test
workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - Run Unit Tests